
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ConvexClerkProvider from "@/components/ui/providers/ConvexClerkProvider";
import StreamClientProvider from "@/components/ui/providers/StreamClientProvider";
import Navbar from "@/components/ui/Navbar";
import { ThemeProvider } from "@/components/ui/providers/ThemeProvider";
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClerkProvider>
          <StreamClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SignedIn>
                <div className="min-h-screen">
                  <Navbar />
                  <main className="px-2 sm:px-4 md:px-6 lg:px-8">
                    {children}
                  </main>
                </div>
              </SignedIn>
              <SignedOut>
                <RedirectToSignIn />
              </SignedOut>
            </ThemeProvider>
            <Toaster />
          </StreamClientProvider>
        </ConvexClerkProvider>
      </body>
    </html>
  );
}
